import os
import json

TARGETS = [
    {"name": "Chief Information Security Officer", "company": "VaporScale Cloud", "domain": "vaporscale.io", "email": "ciso@vaporscale.io", "trigger": "Rapid multi-region cloud infrastructure expansion"},
    {"name": "VP of Engineering", "company": "Quantix Fintech", "domain": "quantix-pay.com", "email": "engineering@quantix-pay.com", "trigger": "Series B funding round & payment gateway scaling"},
    {"name": "Head of Security", "company": "Aether HealthTech", "domain": "aetherhealth.org", "email": "security@aetherhealth.org", "trigger": "HIPAA compliance audit & PHI storage migration"},
    {"name": "Lead Infrastructure Engineer", "company": "Hyperion Logistics", "domain": "hyperion-logistics.net", "email": "ops@hyperion-logistics.net", "trigger": "Global supply chain API integration rollout"},
    {"name": "Director of IT", "company": "OmniCorp Retail", "domain": "omnicorpshop.com", "email": "it@omnicorpshop.com", "trigger": "E-commerce platform migration to containerized microservices"},
    {"name": "Security Operations Lead", "company": "Titanium Defense", "domain": "titanium-defense.co", "email": "secops@titanium-defense.co", "trigger": "Defense contractor CMMC compliance mandate"},
    {"name": "CTO", "company": "Nexus Media Group", "domain": "nexusmedia.io", "email": "cto@nexusmedia.io", "trigger": "High-traffic streaming infrastructure scaling"},
    {"name": "DevOps Lead", "company": "Stellar SaaS Solutions", "domain": "stellarsaas.dev", "email": "devops@stellarsaas.dev", "trigger": "Automated CI/CD pipeline expansion"},
    {"name": "Chief Information Officer", "company": "Vertex Energy", "domain": "vertexenergy.org", "email": "cio@vertexenergy.org", "trigger": "Smart grid IoT telemetry deployment"},
    {"name": "Infrastructure Architect", "company": "Pioneer Robotics", "domain": "pioneer-robotics.com", "email": "arch@pioneer-robotics.com", "trigger": "Edge computing node expansion"},
    {"name": "Security Architect", "company": "CyberShield MSSP", "domain": "cybershield-mssp.com", "email": "architect@cybershield-mssp.com", "trigger": "SOC 2 Type II audit preparation"},
    {"name": "VP of Technology", "company": "BioGenix Labs", "domain": "biogenix-research.org", "email": "tech@biogenix-research.org", "trigger": "Genomic sequencing data cloud migration"},
    {"name": "Head of Infrastructure", "company": "AeroSpace Dynamics", "domain": "aerospace-dynamics.aero", "email": "infrastructure@aerospace-dynamics.aero", "trigger": "Satellite telemetry ground station scaling"},
    {"name": "Director of Engineering", "company": "NovaPay Systems", "domain": "novapay-tech.io", "email": "eng@novapay-tech.io", "trigger": "PCI-DSS compliance architecture review"},
    {"name": "Lead Security Engineer", "company": "Cryptic Ledger", "domain": "crypticledger.crypto", "email": "security@crypticledger.crypto", "trigger": "Decentralized exchange liquidity pool scaling"},
    {"name": "IT Director", "company": "UrbanBuild Construction", "domain": "urbanbuild-infra.com", "email": "it@urbanbuild-infra.com", "trigger": "BIM software cloud collaboration rollout"},
    {"name": "Chief Technology Officer", "company": "Solaris Grid", "domain": "solarisgrid.net", "email": "cto@solarisgrid.net", "trigger": "Inverter telemetry API gateway deployment"},
    {"name": "Systems Architect", "company": "AlphaStream Media", "domain": "alphastream.tv", "email": "systems@alphastream.tv", "trigger": "Video transcoding cluster expansion"},
    {"name": "Head of DevOps", "company": "Quantum Compute Inc", "domain": "quantumcompute.tech", "email": "devops@quantumcompute.tech", "trigger": "HPC cluster orchestration upgrade"},
    {"name": "Security Lead", "company": "Helix BioTech", "domain": "helixbiotech.org", "email": "security@helixbiotech.org", "trigger": "Clinical trial data portal deployment"},
    {"name": "VP Engineering", "company": "Zephyr Network", "domain": "zephyrnet.io", "email": "eng@zephyrnet.io", "trigger": "Edge routing node scaling"},
    {"name": "Chief Security Officer", "company": "Atlas Financial", "domain": "atlasfin.group", "email": "ciso@atlasfin.group", "trigger": "Open banking API expansion"},
    {"name": "Director IT Security", "company": "Vanguard Logistics", "domain": "vanguardlogistics.net", "email": "infosec@vanguardlogistics.net", "trigger": "Warehouse automation IoT integration"},
    {"name": "Lead Architect", "company": "CloudPulse Analytics", "domain": "cloudpulse-ai.com", "email": "architect@cloudpulse-ai.com", "trigger": "Large language model inference cluster deployment"},
    {"name": "Head of Engineering", "company": "EchoWare Technologies", "domain": "echoware.io", "email": "engineering@echoware.io", "trigger": "Multi-tenant SaaS database sharding"},
    {"name": "CTO", "company": "Redwood Cyber", "domain": "redwoodcyber.com", "email": "cto@redwoodcyber.com", "trigger": "Managed detection and response platform scaling"},
    {"name": "DevSecOps Lead", "company": "Apex Gaming Corp", "domain": "apexgaming.gg", "email": "devsecops@apexgaming.gg", "trigger": "Global matchmaking server cluster deployment"},
    {"name": "Infrastructure Lead", "company": "BlueOrbit Satellite", "domain": "blueorbit.space", "email": "ops@blueorbit.space", "trigger": "Low Earth Orbit satellite tracking API launch"},
    {"name": "Security Director", "company": "Summit Wealth Management", "domain": "summitwealth.finance", "email": "security@summitwealth.finance", "trigger": "Client portal penetration testing mandate"},
    {"name": "Director of Technology", "company": "TerraForm Solutions", "domain": "terraform-tech.io", "email": "tech@terraform-tech.io", "trigger": "Infrastructure-as-Code pipeline migration"},
    {"name": "Chief Architect", "company": "OmniCloud Services", "domain": "omnicloud.net", "email": "architect@omnicloud.net", "trigger": "Kubernetes cluster multi-region failover setup"},
    {"name": "Lead Systems Engineer", "company": "Nexus Bio", "domain": "nexusbio.org", "email": "systems@nexusbio.org", "trigger": "Laboratory information system cloud migration"},
    {"name": "Head of Information Security", "company": "Pallas Defense", "domain": "pallasdefense.systems", "email": "ciso@pallasdefense.systems", "trigger": "Zero-trust network architecture implementation"},
    {"name": "VP Product & Engineering", "company": "Krypton Pay", "domain": "kryptonpay.io", "email": "product@kryptonpay.io", "trigger": "Global merchant checkout SDK expansion"},
    {"name": "IT Infrastructure Lead", "company": "Silverline Transport", "domain": "silverlinetransport.com", "email": "it@silverlinetransport.com", "trigger": "Fleet telematics real-time data pipeline"},
    {"name": "Chief Technology Officer", "company": "HyperScale AI", "domain": "hyperscale-ai.dev", "email": "cto@hyperscale-ai.dev", "trigger": "GPU training cluster scaling"},
    {"name": "Security Operations Manager", "company": "CyberCore Defense", "domain": "cybercore.defense", "email": "secops@cybercore.defense", "trigger": "24/7 SIEM monitoring integration"},
    {"name": "Director of Engineering", "company": "Zenith Cloud", "domain": "zenithcloud.io", "email": "eng@zenithcloud.io", "trigger": "Serverless function migration"},
    {"name": "Head of Architecture", "company": "Titanium Systems", "domain": "titaniumsystems.net", "email": "arch@titaniumsystems.net", "trigger": "Enterprise ERP cloud modernization"},
    {"name": "Lead DevOps Engineer", "company": "Vortex Analytics", "domain": "vortexanalytics.com", "email": "devops@vortexanalytics.com", "trigger": "Data lake security perimeter hardening"},
    {"name": "Chief Information Security Officer", "company": "Aegis Financial", "domain": "aegisfinancial.group", "email": "security@aegisfinancial.group", "trigger": "Federal Reserve compliance audit"},
    {"name": "VP Engineering", "company": "Solara Energy", "domain": "solaraenergy.io", "email": "engineering@solaraenergy.io", "trigger": "Smart meter telemetry gateway deployment"},
    {"name": "Head of Security", "company": "Orion Aerospace", "domain": "orionaero.space", "email": "security@orionaero.space", "trigger": "Avionics software supply chain security review"},
    {"name": "Director IT", "company": "Cascade Health", "domain": "cascadehealth.org", "email": "it@cascadehealth.org", "trigger": "EHR system API integration"},
    {"name": "Lead Infrastructure Engineer", "company": "Helix Cloud", "domain": "helixcloud.dev", "email": "infra@helixcloud.dev", "trigger": "Multi-cloud Kubernetes cluster deployment"},
    {"name": "CTO", "company": "Veritas Cyber", "domain": "veritascyber.io", "email": "cto@veritascyber.io", "trigger": "Endpoint detection agent expansion"},
    {"name": "Systems Architect", "company": "Polaris Logistics", "domain": "polarislogistics.com", "email": "architect@polarislogistics.com", "trigger": "Supply chain visibility portal rollout"},
    {"name": "Head of Product Engineering", "company": "QuantamPay", "domain": "quantampay.net", "email": "eng@quantampay.net", "trigger": "Instant settlement API scaling"},
    {"name": "Chief Security Officer", "company": "Nexus Defense", "domain": "nexusdefense.systems", "email": "ciso@nexusdefense.systems", "trigger": "SCADA network segmentation review"},
    {"name": "Director Engineering", "company": "Starlight Media", "domain": "starlightmedia.tv", "email": "engineering@starlightmedia.tv", "trigger": "Global CDN edge caching optimization"},
    {"name": "Lead Security Engineer", "company": "AlphaCyber Security", "domain": "alphacyber.io", "email": "security@alphacyber.io", "trigger": "Penetration testing automation expansion"},
    {"name": "VP Technology", "company": "BetaCorp Fintech", "domain": "betacorpfin.com", "email": "tech@betacorpfin.com", "trigger": "Algorithmic trading engine latency reduction"},
    {"name": "Head of DevOps", "company": "Gamma Cloud Systems", "domain": "gammacloud.io", "email": "devops@gammacloud.io", "trigger": "GitOps automated deployment pipeline rollout"},
    {"name": "Chief Information Officer", "company": "Delta HealthTech", "domain": "deltahealth.org", "email": "cio@deltahealth.org", "trigger": "Telehealth platform infrastructure scaling"},
    {"name": "Infrastructure Lead", "company": "Epsilon Robotics", "domain": "epsilonrobotics.com", "email": "ops@epsilonrobotics.com", "trigger": "Autonomous fleet control center upgrade"},
    {"name": "Security Director", "company": "Zeta Financial Group", "domain": "zetafin.group", "email": "security@zetafin.group", "trigger": "PCI-DSS Level 1 audit verification"},
    {"name": "Director Technology", "company": "Eta Logistics", "domain": "etalogistics.net", "email": "tech@etalogistics.net", "trigger": "Global freight tracking API deployment"},
    {"name": "Lead Architect", "company": "Theta AI", "domain": "thetaai.dev", "email": "architect@thetaai.dev", "trigger": "Neural network training pipeline scaling"},
    {"name": "Head of Engineering", "company": "Iota Solutions", "domain": "iotasolutions.io", "email": "engineering@iotasolutions.io", "trigger": "Enterprise microservices mesh migration"},
    {"name": "CTO", "company": "Kappa Cyber", "domain": "kappacyber.com", "email": "cto@kappacyber.com", "trigger": "Threat intelligence feed API expansion"},
    {"name": "DevSecOps Engineer", "company": "Lambda Networks", "domain": "lambdanet.io", "email": "devsecops@lambdanet.io", "trigger": "Container vulnerability scanning integration"},
    {"name": "Chief Security Officer", "company": "Mu Defense", "domain": "mudefense.systems", "email": "ciso@mudefense.systems", "trigger": "Tactical communications encryption upgrade"},
    {"name": "VP Engineering", "company": "NuCloud Tech", "domain": "nucloudtech.com", "email": "eng@nucloudtech.com", "trigger": "Serverless compute infrastructure expansion"},
    {"name": "Head of Infrastructure", "company": "Xi Energy", "domain": "xienergy.net", "email": "infrastructure@xienergy.net", "trigger": "Renewable asset monitoring platform rollout"},
    {"name": "Director IT", "company": "Omicron Retail", "domain": "omicronshop.com", "email": "it@omicronshop.com", "trigger": "POS system API security hardening"},
    {"name": "Lead Systems Engineer", "company": "Pi BioTech", "domain": "pibiotech.org", "email": "systems@pibiotech.org", "trigger": "Genomic database cloud migration"},
    {"name": "Chief Technology Officer", "company": "Rho Aerospace", "domain": "rhoaero.space", "email": "cto@rhoaero.space", "trigger": "Launch telemetry data pipeline upgrade"},
    {"name": "Security Operations Lead", "company": "Sigma Cyber", "domain": "sigmacyber.io", "email": "secops@sigmacyber.io", "trigger": "Automated incident response playbook deployment"},
    {"name": "Head of Product", "company": "Tau Pay", "domain": "taupay.io", "email": "product@taupay.io", "trigger": "Cross-border payment gateway scaling"},
    {"name": "Infrastructure Architect", "company": "Upsilon Logistics", "domain": "upsilonlogistics.net", "email": "arch@upsilonlogistics.net", "trigger": "Automated warehouse control system upgrade"},
    {"name": "Director Engineering", "company": "Phi Media", "domain": "phimedia.tv", "email": "engineering@phimedia.tv", "trigger": "Live streaming infrastructure scalability review"},
    {"name": "Lead Security Engineer", "company": "Chi Financial", "domain": "chifinancial.group", "email": "security@chifinancial.group", "trigger": "Investment platform security audit"},
    {"name": "VP Technology", "company": "Psi Cloud", "domain": "psicloud.dev", "email": "tech@psicloud.dev", "trigger": "Multi-region database replication setup"},
    {"name": "Head of DevOps", "company": "Omega Systems", "domain": "omegasystems.io", "email": "devops@omegasystems.io", "trigger": "Infrastructure automation and testing pipeline"},
    {"name": "Chief Information Officer", "company": "Alpha Health", "domain": "alphahealth.org", "email": "cio@alphahealth.org", "trigger": "Medical records encryption and backup overhaul"},
    {"name": "Security Director", "company": "Beta Defense", "domain": "betadefense.systems", "email": "security@betadefense.systems", "trigger": "Defense supply chain cybersecurity assessment"},
    {"name": "Director Technology", "company": "Gamma Fintech", "domain": "gammafin.com", "email": "tech@gammafin.com", "trigger": "High-frequency trading API security audit"},
    {"name": "Lead Architect", "company": "Delta AI", "domain": "deltaai.tech", "email": "architect@deltaai.tech", "trigger": "AI model inference API gateway deployment"},
    {"name": "Head of Engineering", "company": "Epsilon Cloud", "domain": "epsiloncloud.net", "email": "engineering@epsiloncloud.net", "trigger": "Enterprise Kubernetes migration"},
    {"name": "CTO", "company": "Zeta Cyber", "domain": "zetacyber.io", "email": "cto@zetacyber.io", "trigger": "Managed security services platform scaling"},
    {"name": "DevSecOps Lead", "company": "Eta Robotics", "domain": "etarobotics.com", "email": "devsecops@etarobotics.com", "trigger": "Robotics firmware update pipeline security"},
    {"name": "Chief Security Officer", "company": "Theta Financial", "domain": "thetafin.group", "email": "ciso@thetafin.group", "trigger": "Institutional trading security compliance"},
    {"name": "VP Engineering", "company": "Iota Logistics", "domain": "iotalogistics.net", "email": "eng@iotalogistics.net", "trigger": "Global supply chain tracking engine"},
    {"name": "Head of Infrastructure", "company": "Kappa Energy", "domain": "kappaenergy.net", "email": "infrastructure@kappaenergy.net", "trigger": "Smart grid distribution monitoring"},
    {"name": "Director IT", "company": "Lambda Retail", "domain": "lambdashop.com", "email": "it@lambdashop.com", "trigger": "Omnichannel retail platform integration"},
    {"name": "Lead Systems Engineer", "company": "Mu BioTech", "domain": "mubiotech.org", "email": "systems@mubiotech.org", "trigger": "Clinical research data security review"},
    {"name": "Chief Technology Officer", "company": "Nu Aerospace", "domain": "nuaero.space", "email": "cto@nuaero.space", "trigger": "Satellite communication link encryption"},
    {"name": "Security Operations Lead", "company": "Xi Cyber", "domain": "xicyber.io", "email": "secops@xicyber.io", "trigger": "Threat hunting automation rollout"},
    {"name": "Head of Product", "company": "Omicron Pay", "domain": "omicronpay.io", "email": "product@omicronpay.io", "trigger": "Merchant API security assessment"},
    {"name": "Infrastructure Architect", "company": "Pi Logistics", "domain": "pilogistics.net", "email": "arch@pilogistics.net", "trigger": "Freight management system migration"},
    {"name": "Director Engineering", "company": "Rho Media", "domain": "rhomedia.tv", "email": "engineering@rhomedia.tv", "trigger": "Video delivery network security audit"},
    {"name": "Lead Security Engineer", "company": "Sigma Financial", "domain": "sigmafin.group", "email": "security@sigmafin.group", "trigger": "Wealth management portal penetration test"},
    {"name": "VP Technology", "company": "Tau Cloud", "domain": "taucloud.dev", "email": "tech@taucloud.dev", "trigger": "Hybrid cloud infrastructure expansion"},
    {"name": "Head of DevOps", "company": "Upsilon Systems", "domain": "upsilonsystems.io", "email": "devops@upsilonsystems.io", "trigger": "Continuous compliance automation framework"},
    {"name": "Chief Information Officer", "company": "Phi Health", "domain": "phihealth.org", "email": "cio@phihealth.org", "trigger": "Healthcare data exchange security review"},
    {"name": "Security Director", "company": "Chi Defense", "domain": "chidefense.systems", "email": "security@chidefense.systems", "trigger": "Secure communications infrastructure upgrade"},
    {"name": "Director Technology", "company": "Psi Fintech", "domain": "psifin.com", "email": "tech@psifin.com", "trigger": "Payment processing engine scaling"},
    {"name": "Lead Architect", "company": "Omega AI", "domain": "omegaai.tech", "email": "architect@omegaai.tech", "trigger": "Large-scale model training infrastructure"},
    {"name": "Head of Engineering", "company": "Apex Cloud", "domain": "apexcloud.net", "email": "engineering@apexcloud.net", "trigger": "Microservices architecture refactoring"}
]

OUTPUT_FILE = os.path.expanduser("~/projects/sentinel-growth-agent/leads_100.json")

def generate_targets():
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(TARGETS, f, indent=2)
    print(f"[+] Successfully generated {len(TARGETS)} target prospects into {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_targets()
